from datetime import datetime, timedelta
import math
import random
from typing import List
from .models import (
    FieldSummary,
    Well,
    ReservoirState,
    WellboreState,
    CSSCycleState,
    SRPOperatingState,
    SurfaceProductionState,
    ReliabilityState,
    OptimizationRecommendation,
    OptimizationCurrentParams,
    OptimizationRecommendedParams,
    OptimizationDeltas,
    PhysicsConstraintCheck,
    ShapFeatureImportance,
    WellHistoryPoint
)

BAGHEWALA_FIELD_SUMMARY = FieldSummary(
    fieldName='Baghewala Heavy Oil Field',
    operator='Oil India Limited (OIL) - Rajasthan Project',
    formation='Jodhpur Sandstone (Bikaner-Nagaur Basin)',
    nativeViscosityRange='10,000 - 13,000 cP @ 50°C (17-19° API)',
    totalWells=23,
    producingWells=16,
    steamingWells=3,
    soakingWells=2,
    cutoffPendingWells=2,
    totalOilRate_bopd=914.5,
    totalSteamInjection_t_day=380.0,
    averageSor=3.42,
    averagePumpFillage_pct=78.4,
    averageFleetViscosity_cp=340.0,
    activeRodRiskAlerts=3,
    dailyEnergy_mwh=18.6,
    fleetHealthAvg_pct=84.2,
)

def generate_history(base_oil: float, base_temp: float, base_visc: float, base_sor: float, base_spm: float, base_fillage: float, base_risk: float) -> List[WellHistoryPoint]:
    history: List[WellHistoryPoint] = []
    now = datetime.utcnow()
    for i in range(29, -1, -1):
        day_date = now - timedelta(days=i)
        oil = max(12.0, round(base_oil * (1.0 + (15.0 - i) * 0.02) + (random.uniform(-2, 2)), 1))
        temp = max(52.0, round(base_temp + (15.0 - i) * 1.8 + (random.uniform(-1, 1)), 1))
        visc = float(round(11000.0 * math.exp(-0.028 * (temp - 48.0))))
        sor = round(base_sor + ( (i - 15) * 0.08 if i > 15 else 0.0 ) + random.uniform(-0.1, 0.1), 2)
        fillage = float(min(98, max(45, round(base_fillage + random.uniform(-3, 3)))))
        risk = float(min(95, max(10, round(base_risk + (4 if i < 5 else -2) + random.uniform(0, 3)))))

        history.append(WellHistoryPoint(
            timestamp=day_date.strftime('%Y-%m-%d'),
            oilRate_bopd=oil,
            temp_c=temp,
            viscosity_cp=visc,
            sor=sor,
            spm=round(base_spm + random.uniform(-0.2, 0.2), 1),
            pumpFillage_pct=fillage,
            rodRisk_pct=risk
        ))
    return history

INITIAL_WELLS: List[Well] = [
    Well(
        id='BGW-07',
        name='Baghewala Well #07',
        pad='Pad-North Alpha',
        status='WARNING',
        stage='PRODUCTION',
        reservoir=ReservoirState(
            reservoirZone='Jodhpur Sandstone Upper Member',
            reservoirDepth_m=1148,
            initialPressure_psi=1420,
            currentPressure_psi=1180,
            nativeTemp_c=48,
            nearWellboreTemp_c=74,
            nativeViscosity_cp=11500,
            effectiveViscosity_cp=820,
            oilGravity_api=18.2,
            permeability_md=480,
            netPay_m=14.5,
            productivityIndex_bopd_psi=0.12,
            thermalRadius_m=22.4,
        ),
        wellbore=WellboreState(
            casingSize_in=9.625,
            tubingSize_in=3.5,
            pumpDepth_m=1080,
            fluidLevel_m=340,
            flowingBottomholePressure_psi=620,
            tubingHeadPressure_psi=110,
            casingHeadPressure_psi=45,
            wellheadTemp_c=62,
            gasAnchorInstalled=True,
        ),
        css=CSSCycleState(
            cycleNumber=4,
            stage='PRODUCTION',
            stageDayCount=68,
            targetSteamVolume_m3=2400,
            cumulativeSteamInjected_m3=2420,
            steamQuality_pct=78,
            steamInjectionPressure_psi=1850,
            steamTemp_c=260,
            soakDaysTotal=5,
            soakDaysRemaining=0,
            currentSor=4.85,
            cumulativeOilThisCycle_bbl=3840,
            economicCutoffPredictedDay=75,
            recommendedNextCycleDate='2026-09-12',
        ),
        srp=SRPOperatingState(
            spm=5.8,
            strokeLength_in=74,
            vfdFrequency_hz=48.3,
            motorPower_kw=28.5,
            motorCurrent_a=44.2,
            peakPolishedRodLoad_lbs=23800,
            minPolishedRodLoad_lbs=6200,
            goodmanStressRatio_pct=88.4,
            pumpFillage_pct=61,
            volumetricEfficiency_pct=64,
            rodFloatRisk_pct=74,
            pumpOffRisk_pct=32,
            dailyEnergy_kwh=540,
            energyPerBarrel_kwh=12.8,
        ),
        production=SurfaceProductionState(
            oilRate_bopd=42.2,
            liquidRate_blpd=78.0,
            waterCut_pct=45.9,
            gasRate_mscfd=8.4,
            gasOilRatio_scf_bbl=199,
        ),
        reliability=ReliabilityState(
            healthScore_pct=68,
            rodFailureProbability_pct=72,
            pumpFailureProbability_pct=35,
            predictedRul_days=14,
            sensorDataQuality_pct=94,
            leadTimeBenchmark_days=13.9,
            failureMechanismRisk='Viscous Downstroke Drag & Rod Compression Buckling',
            anomaliesDetected=[
                'Dynacard indicates heavy viscous friction causing retarded downstroke',
                'Polished rod stress amplitude nearing API Modified Goodman Envelope (88.4%)',
                'Current SOR (4.85) nearing economic cut-off threshold (5.20)'
            ],
        ),
        activeRecommendation=OptimizationRecommendation(
            id='REC-BGW07-20260904',
            wellId='BGW-07',
            generatedAt='2026-09-04T08:30:00Z',
            status='PENDING_APPROVAL',
            current=OptimizationCurrentParams(
                spm=5.8,
                strokeLength_in=74,
                vfdFrequency_hz=48.3,
                steamVolume_m3=2400,
                soakDays=5,
                oilRate_bopd=42.2,
                sor=4.85,
                rodFailureRisk_pct=72,
                dailyEnergy_kwh=540,
            ),
            recommended=OptimizationRecommendedParams(
                spm=4.9,
                strokeLength_in=74,
                vfdFrequency_hz=40.8,
                steamVolume_m3=2650,
                soakDays=5,
                projectedOilRate_bopd=45.8,
                projectedSor=3.92,
                projectedRodFailureRisk_pct=24,
                projectedDailyEnergy_kwh=460,
            ),
            deltas=OptimizationDeltas(
                deltaOilRate_bopd=3.6,
                deltaOilRatePct=8.5,
                deltaSorPct=-19.2,
                deltaRodRiskPct=-66.7,
                deltaDailyEnergyPct=-14.8,
                projectedMonthlyNetBenefit_inr=435000,
            ),
            engineeringRationale=[
                'Reduce SRP pumping speed from 5.8 SPM to 4.9 SPM (-15.5% VFD frequency) to eliminate rod float drag under 820 cP crude.',
                'Lowering stroke speed allows rod string to fall by gravity without downstroke compression, preventing rod buckling and fatigue.',
                'Volumetric fillage is projected to rise from 61% to 82% as intake valves seat properly in viscous crude.',
                'Schedule CSS Cycle #5 with 2,650 m³ steam @ 80% quality before SOR crosses the 5.20 economic cut-off.'
            ],
            physicsConstraintsChecks=[
                PhysicsConstraintCheck(name='API Spec 11L Modified Goodman Stress', status='PASS', limit='< 85.0%', actual='64.2%'),
                PhysicsConstraintCheck(name='Downstroke Rod Float Drag Index', status='PASS', limit='< 40%', actual='28.4%'),
                PhysicsConstraintCheck(name='Reservoir Sand Cavitation Drawdown Limit', status='PASS', limit='< 650 psi', actual='560 psi'),
                PhysicsConstraintCheck(name='VFD Inverter Thermal Window', status='PASS', limit='30 - 55 Hz', actual='40.8 Hz'),
            ],
            shapFeatureImportance=[
                ShapFeatureImportance(feature='Effective Downhole Viscosity (cP)', importance=0.42, direction='negative'),
                ShapFeatureImportance(feature='SRP Stroke Speed (SPM)', importance=0.31, direction='negative'),
                ShapFeatureImportance(feature='Dynamic Fluid Level Head (m)', importance=0.15, direction='positive'),
                ShapFeatureImportance(feature='Steam Injection Quality (%)', importance=0.12, direction='positive'),
            ]
        ),
        history=generate_history(42, 74, 820, 4.85, 5.8, 61, 74)
    ),
    Well(
        id='BGW-12',
        name='Baghewala Well #12',
        pad='Pad-North Beta',
        status='OPTIMAL',
        stage='PRODUCTION',
        reservoir=ReservoirState(
            reservoirZone='Jodhpur Sandstone Upper Member',
            reservoirDepth_m=1152,
            initialPressure_psi=1425,
            currentPressure_psi=1290,
            nativeTemp_c=48,
            nearWellboreTemp_c=132,
            nativeViscosity_cp=11500,
            effectiveViscosity_cp=115,
            oilGravity_api=18.4,
            permeability_md=520,
            netPay_m=16.0,
            productivityIndex_bopd_psi=0.28,
            thermalRadius_m=28.6,
        ),
        wellbore=WellboreState(
            casingSize_in=9.625,
            tubingSize_in=3.5,
            pumpDepth_m=1095,
            fluidLevel_m=210,
            flowingBottomholePressure_psi=780,
            tubingHeadPressure_psi=145,
            casingHeadPressure_psi=55,
            wellheadTemp_c=98,
            gasAnchorInstalled=True,
        ),
        css=CSSCycleState(
            cycleNumber=3,
            stage='PRODUCTION',
            stageDayCount=22,
            targetSteamVolume_m3=2800,
            cumulativeSteamInjected_m3=2850,
            steamQuality_pct=81,
            steamInjectionPressure_psi=1920,
            steamTemp_c=270,
            soakDaysTotal=6,
            soakDaysRemaining=0,
            currentSor=2.45,
            cumulativeOilThisCycle_bbl=4250,
            economicCutoffPredictedDay=92,
            recommendedNextCycleDate='2026-11-20',
        ),
        srp=SRPOperatingState(
            spm=5.4,
            strokeLength_in=86,
            vfdFrequency_hz=45.0,
            motorPower_kw=32.0,
            motorCurrent_a=49.0,
            peakPolishedRodLoad_lbs=21200,
            minPolishedRodLoad_lbs=7800,
            goodmanStressRatio_pct=68.2,
            pumpFillage_pct=89,
            volumetricEfficiency_pct=88,
            rodFloatRisk_pct=18,
            pumpOffRisk_pct=12,
            dailyEnergy_kwh=620,
            energyPerBarrel_kwh=9.4,
        ),
        production=SurfaceProductionState(
            oilRate_bopd=66.0,
            liquidRate_blpd=98.0,
            waterCut_pct=32.7,
            gasRate_mscfd=14.2,
            gasOilRatio_scf_bbl=215,
        ),
        reliability=ReliabilityState(
            healthScore_pct=94,
            rodFailureProbability_pct=12,
            pumpFailureProbability_pct=8,
            predictedRul_days=180,
            sensorDataQuality_pct=98,
            leadTimeBenchmark_days=13.9,
            failureMechanismRisk='Normal Thermal Production Regime',
            anomaliesDetected=[],
        ),
        history=generate_history(66, 132, 115, 2.45, 5.4, 89, 18)
    ),
    Well(
        id='BGW-03',
        name='Baghewala Well #03',
        pad='Pad-South Alpha',
        status='OPTIMAL',
        stage='INJECTION',
        reservoir=ReservoirState(
            reservoirZone='Jodhpur Sandstone Middle Member',
            reservoirDepth_m=1140,
            initialPressure_psi=1410,
            currentPressure_psi=1480,
            nativeTemp_c=48,
            nearWellboreTemp_c=248,
            nativeViscosity_cp=11200,
            effectiveViscosity_cp=24,
            oilGravity_api=18.0,
            permeability_md=460,
            netPay_m=13.8,
            productivityIndex_bopd_psi=0.42,
            thermalRadius_m=19.8,
        ),
        wellbore=WellboreState(
            casingSize_in=9.625,
            tubingSize_in=3.5,
            pumpDepth_m=1075,
            fluidLevel_m=0,
            flowingBottomholePressure_psi=1850,
            tubingHeadPressure_psi=1720,
            casingHeadPressure_psi=320,
            wellheadTemp_c=240,
            gasAnchorInstalled=True,
        ),
        css=CSSCycleState(
            cycleNumber=5,
            stage='INJECTION',
            stageDayCount=9,
            targetSteamVolume_m3=2600,
            cumulativeSteamInjected_m3=1980,
            steamQuality_pct=82,
            steamInjectionPressure_psi=1950,
            steamTemp_c=275,
            soakDaysTotal=6,
            soakDaysRemaining=6,
            currentSor=0.0,
            cumulativeOilThisCycle_bbl=0,
            economicCutoffPredictedDay=85,
            recommendedNextCycleDate='2026-09-08',
        ),
        srp=SRPOperatingState(
            spm=0.0,
            strokeLength_in=74,
            vfdFrequency_hz=0.0,
            motorPower_kw=0.0,
            motorCurrent_a=0.0,
            peakPolishedRodLoad_lbs=0,
            minPolishedRodLoad_lbs=0,
            goodmanStressRatio_pct=0.0,
            pumpFillage_pct=0,
            volumetricEfficiency_pct=0,
            rodFloatRisk_pct=0,
            pumpOffRisk_pct=0,
            dailyEnergy_kwh=0,
            energyPerBarrel_kwh=0,
        ),
        production=SurfaceProductionState(
            oilRate_bopd=0.0,
            liquidRate_blpd=0.0,
            waterCut_pct=0.0,
            gasRate_mscfd=0.0,
            gasOilRatio_scf_bbl=0,
        ),
        reliability=ReliabilityState(
            healthScore_pct=96,
            rodFailureProbability_pct=5,
            pumpFailureProbability_pct=6,
            predictedRul_days=210,
            sensorDataQuality_pct=99,
            leadTimeBenchmark_days=13.9,
            failureMechanismRisk='Active High-Pressure Steam Injection',
            anomaliesDetected=[],
        ),
        history=generate_history(0, 248, 24, 0, 0, 0, 5)
    ),
    Well(
        id='BGW-09',
        name='Baghewala Well #09',
        pad='Pad-North Beta',
        status='OPTIMAL',
        stage='SOAKING',
        reservoir=ReservoirState(
            reservoirZone='Jodhpur Sandstone Upper Member',
            reservoirDepth_m=1156,
            initialPressure_psi=1430,
            currentPressure_psi=1520,
            nativeTemp_c=48,
            nearWellboreTemp_c=215,
            nativeViscosity_cp=11800,
            effectiveViscosity_cp=32,
            oilGravity_api=18.1,
            permeability_md=495,
            netPay_m=15.2,
            productivityIndex_bopd_psi=0.38,
            thermalRadius_m=26.2,
        ),
        wellbore=WellboreState(
            casingSize_in=9.625,
            tubingSize_in=3.5,
            pumpDepth_m=1090,
            fluidLevel_m=0,
            flowingBottomholePressure_psi=1460,
            tubingHeadPressure_psi=840,
            casingHeadPressure_psi=210,
            wellheadTemp_c=185,
            gasAnchorInstalled=True,
        ),
        css=CSSCycleState(
            cycleNumber=4,
            stage='SOAKING',
            stageDayCount=3,
            targetSteamVolume_m3=2700,
            cumulativeSteamInjected_m3=2740,
            steamQuality_pct=80,
            steamInjectionPressure_psi=1880,
            steamTemp_c=268,
            soakDaysTotal=5,
            soakDaysRemaining=2,
            currentSor=0.0,
            cumulativeOilThisCycle_bbl=0,
            economicCutoffPredictedDay=90,
            recommendedNextCycleDate='2026-09-06',
        ),
        srp=SRPOperatingState(
            spm=0.0,
            strokeLength_in=86,
            vfdFrequency_hz=0.0,
            motorPower_kw=0.0,
            motorCurrent_a=0.0,
            peakPolishedRodLoad_lbs=0,
            minPolishedRodLoad_lbs=0,
            goodmanStressRatio_pct=0.0,
            pumpFillage_pct=0,
            volumetricEfficiency_pct=0,
            rodFloatRisk_pct=0,
            pumpOffRisk_pct=0,
            dailyEnergy_kwh=0,
            energyPerBarrel_kwh=0,
        ),
        production=SurfaceProductionState(
            oilRate_bopd=0.0,
            liquidRate_blpd=0.0,
            waterCut_pct=0.0,
            gasRate_mscfd=0.0,
            gasOilRatio_scf_bbl=0,
        ),
        reliability=ReliabilityState(
            healthScore_pct=95,
            rodFailureProbability_pct=7,
            pumpFailureProbability_pct=7,
            predictedRul_days=195,
            sensorDataQuality_pct=97,
            leadTimeBenchmark_days=13.9,
            failureMechanismRisk='Thermal Soaking & Heat Diffusion',
            anomaliesDetected=[],
        ),
        history=generate_history(0, 215, 32, 0, 0, 0, 7)
    ),
    Well(
        id='BGW-15',
        name='Baghewala Well #15',
        pad='Pad-South Beta',
        status='CRITICAL',
        stage='CYCLE_CUTOFF_PENDING',
        reservoir=ReservoirState(
            reservoirZone='Jodhpur Sandstone Middle Member',
            reservoirDepth_m=1162,
            initialPressure_psi=1415,
            currentPressure_psi=1080,
            nativeTemp_c=48,
            nearWellboreTemp_c=58,
            nativeViscosity_cp=11600,
            effectiveViscosity_cp=2450,
            oilGravity_api=17.9,
            permeability_md=440,
            netPay_m=13.0,
            productivityIndex_bopd_psi=0.06,
            thermalRadius_m=17.4,
        ),
        wellbore=WellboreState(
            casingSize_in=9.625,
            tubingSize_in=3.5,
            pumpDepth_m=1100,
            fluidLevel_m=510,
            flowingBottomholePressure_psi=480,
            tubingHeadPressure_psi=85,
            casingHeadPressure_psi=35,
            wellheadTemp_c=52,
            gasAnchorInstalled=True,
        ),
        css=CSSCycleState(
            cycleNumber=3,
            stage='CYCLE_CUTOFF_PENDING',
            stageDayCount=84,
            targetSteamVolume_m3=2300,
            cumulativeSteamInjected_m3=2310,
            steamQuality_pct=77,
            steamInjectionPressure_psi=1820,
            steamTemp_c=258,
            soakDaysTotal=5,
            soakDaysRemaining=0,
            currentSor=5.64,
            cumulativeOilThisCycle_bbl=2580,
            economicCutoffPredictedDay=78,
            recommendedNextCycleDate='2026-09-02',
        ),
        srp=SRPOperatingState(
            spm=4.2,
            strokeLength_in=74,
            vfdFrequency_hz=35.0,
            motorPower_kw=34.5,
            motorCurrent_a=52.8,
            peakPolishedRodLoad_lbs=26100,
            minPolishedRodLoad_lbs=4100,
            goodmanStressRatio_pct=94.2,
            pumpFillage_pct=44,
            volumetricEfficiency_pct=48,
            rodFloatRisk_pct=88,
            pumpOffRisk_pct=48,
            dailyEnergy_kwh=680,
            energyPerBarrel_kwh=32.4,
        ),
        production=SurfaceProductionState(
            oilRate_bopd=21.0,
            liquidRate_blpd=62.0,
            waterCut_pct=66.1,
            gasRate_mscfd=4.2,
            gasOilRatio_scf_bbl=200,
        ),
        reliability=ReliabilityState(
            healthScore_pct=52,
            rodFailureProbability_pct=86,
            pumpFailureProbability_pct=54,
            predictedRul_days=6,
            sensorDataQuality_pct=92,
            leadTimeBenchmark_days=13.9,
            failureMechanismRisk='Extreme Viscous Drag / Fatigue Failure Imminent',
            anomaliesDetected=[
                'SOR (5.64) has breached economic cut-off limit of 5.20',
                'Crude cooled to 58°C, effective viscosity reached 2,450 cP',
                'Rod float risk exceeds 88%, severe downstroke retarding detected'
            ],
        ),
        history=generate_history(21, 58, 2450, 5.64, 4.2, 44, 88)
    ),
    Well(
        id='BGW-21',
        name='Baghewala Well #21',
        pad='Pad-East Alpha',
        status='OPTIMAL',
        stage='PRODUCTION',
        reservoir=ReservoirState(
            reservoirZone='Jodhpur Sandstone Upper Member',
            reservoirDepth_m=1144,
            initialPressure_psi=1425,
            currentPressure_psi=1240,
            nativeTemp_c=48,
            nearWellboreTemp_c=108,
            nativeViscosity_cp=11400,
            effectiveViscosity_cp=240,
            oilGravity_api=18.3,
            permeability_md=510,
            netPay_m=15.0,
            productivityIndex_bopd_psi=0.22,
            thermalRadius_m=24.5,
        ),
        wellbore=WellboreState(
            casingSize_in=9.625,
            tubingSize_in=3.5,
            pumpDepth_m=1085,
            fluidLevel_m=260,
            flowingBottomholePressure_psi=690,
            tubingHeadPressure_psi=125,
            casingHeadPressure_psi=48,
            wellheadTemp_c=84,
            gasAnchorInstalled=True,
        ),
        css=CSSCycleState(
            cycleNumber=4,
            stage='PRODUCTION',
            stageDayCount=41,
            targetSteamVolume_m3=2500,
            cumulativeSteamInjected_m3=2530,
            steamQuality_pct=79,
            steamInjectionPressure_psi=1870,
            steamTemp_c=264,
            soakDaysTotal=5,
            soakDaysRemaining=0,
            currentSor=3.15,
            cumulativeOilThisCycle_bbl=5040,
            economicCutoffPredictedDay=82,
            recommendedNextCycleDate='2026-10-15',
        ),
        srp=SRPOperatingState(
            spm=5.6,
            strokeLength_in=86,
            vfdFrequency_hz=46.6,
            motorPower_kw=30.2,
            motorCurrent_a=46.5,
            peakPolishedRodLoad_lbs=22400,
            minPolishedRodLoad_lbs=7100,
            goodmanStressRatio_pct=74.5,
            pumpFillage_pct=84,
            volumetricEfficiency_pct=82,
            rodFloatRisk_pct=34,
            pumpOffRisk_pct=21,
            dailyEnergy_kwh=580,
            energyPerBarrel_kwh=11.2,
        ),
        production=SurfaceProductionState(
            oilRate_bopd=51.8,
            liquidRate_blpd=84.0,
            waterCut_pct=38.3,
            gasRate_mscfd=11.0,
            gasOilRatio_scf_bbl=212,
        ),
        reliability=ReliabilityState(
            healthScore_pct=88,
            rodFailureProbability_pct=22,
            pumpFailureProbability_pct=15,
            predictedRul_days=110,
            sensorDataQuality_pct=96,
            leadTimeBenchmark_days=13.9,
            failureMechanismRisk='Stable Intermediate Production',
            anomaliesDetected=[],
        ),
        history=generate_history(51.8, 108, 240, 3.15, 5.6, 84, 34)
    )
]
